#!/usr/bin/env python3
"""
bulk_keyword_fix.py — Generate WP-CLI commands to bulk-set Rank Math focus keywords
for all service_areas posts that are missing them.

Usage:
    python3 bulk_keyword_fix.py [--dry-run]

Outputs a shell script of wp-cli commands to stdout.
Run on the server: python3 bulk_keyword_fix.py | bash
"""

import subprocess
import sys
import json

WP_PATH = "/home/u167650519/domains/smartsolutionappliances.com/public_html"
WP_BASE = ["wp", f"--path={WP_PATH}", "--allow-root"]


def run_wp(*args):
    result = subprocess.run(WP_BASE + list(args), capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    return result.stdout.strip()


def get_service_area_posts():
    out = run_wp("post", "list", "--post_type=service_areas",
                 "--fields=ID,post_title", "--format=json", "--posts_per_page=100")
    return json.loads(out)


def get_focus_keyword(post_id):
    result = subprocess.run(
        WP_BASE + ["post", "meta", "get", str(post_id), "rank_math_focus_keyword"],
        capture_output=True, text=True
    )
    return result.stdout.strip()


def title_to_keyword(title):
    # "Richmond District (94121)" → "richmond district appliance repair"
    clean = title.replace("(", "").replace(")", "").strip().lower()
    parts = [p for p in clean.split() if not p.isdigit()]
    return " ".join(parts) + " appliance repair"


def main():
    dry_run = "--dry-run" in sys.argv
    posts = get_service_area_posts()
    missing = []

    for post in posts:
        kw = get_focus_keyword(post["ID"])
        if not kw:
            missing.append(post)

    print(f"# Found {len(missing)} posts missing focus keywords", file=sys.stderr)
    print("#!/bin/bash")
    print(f"# Bulk Rank Math focus keyword fixer — {len(missing)} posts")
    print("# Generated by bulk_keyword_fix.py")
    print()

    wp_prefix = f"wp --path={WP_PATH} --allow-root"
    for post in missing:
        keyword = title_to_keyword(post["post_title"])
        if dry_run:
            print(f"# {post['post_title']} (ID {post['ID']}) → '{keyword}'")
        else:
            print(f'{wp_prefix} post meta update {post["ID"]} rank_math_focus_keyword "{keyword}"')


if __name__ == "__main__":
    main()
